import { readdir, readFile } from 'node:fs/promises';
import { describe, expect, it } from 'vitest';

describe('documentation', () => {
  it('documents installation, CLI commands, contracts, and roadmap', async () => {
    const readme = await readFile('README.md', 'utf8');
    const agents = await readFile('AGENTS.md', 'utf8');
    const cli = await readFile('docs/CLI.md', 'utf8');
    const contracts = await readFile('docs/OUTPUT_CONTRACTS.md', 'utf8');
    const agentBenchmarks = await readFile('docs/AGENT_BENCHMARKS.md', 'utf8');
    const roadmap = await readFile('docs/ROADMAP.md', 'utf8');
    const vision = await readFile('docs/PRODUCT_VISION.md', 'utf8');
    const backlog = await readFile('docs/BACKLOG.md', 'utf8');
    const readingMetrics = await readFile('docs/READING_METRICS_STRATEGY.md', 'utf8');
    const benchmarkFixtures = await readdir('benchmarks/fixtures');
    const benchmarkTasks = await readdir('benchmarks/tasks');

    expect(readme).toContain('bpmn-agent-cli');
    expect(readme).toContain('/extensions install https://github.com/killreal777/bpmn-agent-cli');
    expect(readme).toContain('/plugin marketplace add killreal777/bpmn-agent-cli');
    expect(agents).toContain('Do not implement a custom BPMN parser');
    expect(agents).toContain('npm test');
    expect(cli).toContain('bpmn-agent-cli overview process.bpmn');
    expect(cli).toContain('bpmn-agent-cli to-json process.bpmn --preset optimized');
    expect(cli).toContain('bpmn-agent-cli participants process.bpmn');
    expect(cli).toContain('bpmn-agent-cli variables process.bpmn --element Call_SubProcess');
    expect(cli).toContain('bpmn-agent-cli call-activity process.bpmn --id Call_SubProcess');
    expect(cli).toContain('bpmn-agent-cli diff --base before.bpmn --candidate after.bpmn');
    expect(cli).toContain('bpmn-agent-cli impact process.bpmn --id Task_1');
    expect(cli).toContain('bpmn-agent-cli review process.bpmn');
    expect(cli).toContain('bpmn-agent-cli lanes process.bpmn --element Task_1');
    expect(cli).toContain('bpmn-agent-cli events process.bpmn --type boundary');
    expect(cli).toContain('bpmn-agent-cli subprocess process.bpmn --id SubProcess_1');
    expect(cli).toContain('bpmn-agent-cli path process.bpmn --from StartEvent_1 --to EndEvent_1');
    expect(cli).toContain('bpmn-agent-cli export process.bpmn --format markdown');
    expect(cli).toContain('bpmn-agent-cli rename process.bpmn --id Task_1 --name "Review"');
    expect(cli).toContain('bpmn-agent-cli documentation process.bpmn --id Task_1 --text "Review"');
    expect(cli).toContain('bpmn-agent-cli implementation process.bpmn --id Service_1 --kind delegateExpression --value');
    expect(cli).toContain('bpmn-agent-cli format process.bpmn --write -o tmp/formatted.bpmn');
    expect(cli).toContain('bpmn-agent-cli insert-task-between process.bpmn --flow Flow_A_B --id Task_New --name "Review"');
    expect(cli).toContain('bpmn-agent-cli connect process.bpmn --from Task_A --to Task_B --id Flow_A_B');
    expect(cli).toContain('bpmn-agent-cli delete-safe process.bpmn --id Task_1');
    expect(cli).toContain('bpmn-agent-cli add-boundary-event process.bpmn --attached-to Task_1 --id Boundary_Timeout');
    expect(readme).toContain('bpmn-agent-cli path process.bpmn --from StartEvent_1 --to EndEvent_1');
    expect(readme).toContain('bpmn-agent-cli call-activity process.bpmn --id Call_SubProcess');
    expect(readme).toContain('bpmn-agent-cli diff --base before.bpmn --candidate after.bpmn');
    expect(readme).toContain('bpmn-agent-cli impact process.bpmn --id Activity_CheckClient');
    expect(readme).toContain('bpmn-agent-cli review process.bpmn');
    expect(readme).toContain('bpmn-agent-cli export process.bpmn --format markdown');
    expect(contracts).toContain('ELEMENT_NOT_FOUND');
    expect(contracts).toContain('ElementDetails');
    expect(contracts).toContain('AgentContextResult');
    expect(contracts).toContain('CallActivityElementDetails');
    expect(contracts).toContain('callActivityMappings');
    expect(contracts).toContain('VariablesResult');
    expect(contracts).toContain('CallActivityResult');
    expect(contracts).toContain('DiffResult');
    expect(contracts).toContain('ImpactResult');
    expect(contracts).toContain('ReviewResult');
    expect(contracts).toContain('ValidateResult');
    expect(contracts).toContain('CALL_ACTIVITY_WITHOUT_MAPPINGS');
    expect(contracts).toContain('CONDITION_VARIABLE_WITHOUT_PRODUCER');
    expect(contracts).toContain('SERVICE_TASK_MISSING_IMPLEMENTATION');
    expect(contracts).toContain('UNREACHABLE_FLOW_NODE');
    expect(contracts).toContain('CALL_ACTIVITY_MISSING_CALLED_ELEMENT');
    expect(contracts).toContain('ParticipantsResult');
    expect(contracts).toContain('LanesResult');
    expect(contracts).toContain('EventsResult');
    expect(contracts).toContain('SubprocessResult');
    expect(contracts).toContain('PathResult');
    expect(contracts).toContain('ExportResult');
    expect(contracts).toContain('RenameResult');
    expect(contracts).toContain('DocumentationResult');
    expect(contracts).toContain('ImplementationPatchResult');
    expect(contracts).toContain('FormatResult');
    expect(contracts).toContain('InsertTaskBetweenResult');
    expect(contracts).toContain('ConnectResult');
    expect(contracts).toContain('DeleteSafeResult');
    expect(contracts).toContain('AddBoundaryEventResult');
    expect(roadmap).toContain('P0');
    expect(roadmap).toContain('P1-A');
    expect(roadmap).toContain('P1');
    expect(roadmap).toContain('P2');
    expect(roadmap).toContain('context --profile agent');
    expect(vision).toContain('Product Vision');
    expect(vision).toContain('Dry-run');
    expect(vision).toContain('Metric-first reading');
    expect(backlog).toContain('Product Backlog');
    expect(backlog).toContain('Reading Metrics Foundation');
    expect(backlog).toContain('Benchmark Runner And Comparison Report');
    expect(backlog).toContain('variables');
    expect(backlog).toContain('call-activity');
    expect(backlog).toContain('BL-012: `call-activity`');
    expect(backlog).toContain('JSON Conversion Modernization');
    expect(backlog).toContain('BL-015: `diff`');
    expect(backlog).toContain('BL-018: `impact`');
    expect(backlog).toContain('BL-019: `review`');
    expect(backlog).not.toContain('Legacy `to-json` Removal Plan');
    expect(contracts).toContain('JsonConversionResult');
    expect(backlog).toContain('delete-safe');
    expect(backlog).toContain('add-boundary-event');
    expect(backlog).toContain('BPMN Lint Rules');
    expect(backlog).toContain('Variable-Aware Lint Rules');
    expect(backlog).toContain('BPMN Lint Rules');
    expect(backlog).toContain('Status: `implemented`');
    expect(readingMetrics).toContain('Reading Optimization Metrics Strategy');
    expect(readingMetrics).toContain('tokens_per_successful_task');
    expect(readingMetrics).toContain('xml_fallback_rate');
    expect(agentBenchmarks).toContain('benchmark:agent');
    expect(agentBenchmarks).toContain('benchmark:agent:refs');
    expect(agentBenchmarks).toContain('--baseline-ref');
    expect(agentBenchmarks).toContain('--candidate-ref');
    expect(agentBenchmarks).toContain('--agent codex');
    expect(agentBenchmarks).toContain('answerCorrectnessScore');
    expect(benchmarkFixtures.filter((file) => file.endsWith('.bpmn')).length).toBeGreaterThanOrEqual(5);
    expect(benchmarkTasks.filter((file) => file.endsWith('.json')).length).toBeGreaterThanOrEqual(20);
  });
});
